image: gitpod/workspace-base

tasks:
- name: preview
  command: gp preview https://github.com/BGAcademy23/ncbidatasets/blob/main/docs/NCBI-datasets-cli.md

- name: install mamba
  command: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
